#ifndef _PIXELS_CONFIG_HPP

#define DEFAULT_PRICE 500
#define FEE_PERCENTAGE 25

#define PRICE_MULTIPLIER 1.35
#define CANVAS_DURATION 60 * 60 * 24
#define MAX_COORDINATE_X_PLUS_ONE 1000
#define MAX_COORDINATE_Y_PLUS_ONE 1000
#define PIXELS_PER_ROW 50

#define PATRON_BONUS_PERCENTAGE_POINTS 40
#define POT_PERCENTAGE_POINTS 25

// number of pixels sold anything may be withdrawn
#define WITHDRAW_PIXELS_THRESHOLD 150000

#define REFERRER_PERCENTAGE_POINTS 8
// TEAM_PERCENTAGE == 27
#define PRECISION_BASE 1e16
#define TEAM_ACCOUNT N(ceoimondev11)

#define WITHDRAW_QUOTA 10000000  // 1000 EOS

#endif
